### ISSUE TITLE
[DOCUMENTATION]: Javadoc Para a Classe Agent

### ISSUE THREAD

**Issue by profpantoja** [profpantoja/chonGame#18]
Criar o **javadoc** para a classe **Agent**.
Observar os estilos esperados, a padronização e o padrão disponível:
A documentação deve estar em inglês.

- https://pt.wikipedia.org/wiki/Javadoc
- https://www.dio.me/articles/javadoc-documentando-seu-codigo-em-java

**Comment by joaovictorramos** [comment]
Criada a branch com a documentação da classe Agent com Javadoc: https://github.com/profpantoja/chonGame/tree/joao-ramos-javadoc-for-agent-class

**Comment by profpantoja** [comment]
Issue completada por @joaovictorramos.
