### ISSUE TITLE
[DOCUMENTATION]: Javadoc Para a Classe Environment

### ISSUE THREAD

**Issue by profpantoja** [profpantoja/chonGame#19]
Criar o **javadoc** para a classe **Environment**.
Observar os estilos esperados, a padronização e o padrão disponível:
A documentação deve estar em inglês.

- https://pt.wikipedia.org/wiki/Javadoc
- https://www.dio.me/articles/javadoc-documentando-seu-codigo-em-java

**Comment by joaogabreu** [comment]
Criado a branch com a documentação da classe Environment com Javadoc: https://github.com/profpantoja/chonGame/tree/wip-joao-abreu
